### ISSUE TITLE
I cannot for the life of me figure out how to get the pause menu to open

### ISSUE THREAD

**Issue by aftrosrs** [Maaack/Godot-Menus-Template#15]
I'm not sure which files you would want to see, so i suppose i'll wait, theres no errors or anything, but nothng i've looked at seems to work.

**Comment by Maaack** [comment]
Hey, the Pause Menu is currently included in the full [game template ](https://github.com/Maaack/Godot-Game-Template). You opened this issue on the Menus Template, which doesn't currently include the pause menu. I'm not sure if that's the issue here. There isn't an example game/scene to pause in this repo, but I could include the menu anyway.

In the game template, the pause menu can be brought up within a game scene by pressing the `Esc` key, or a gamepad's menu button.

**Comment by aftrosrs** [comment]
ah, see you have like 3 different versions that look very similar and have super similar names. I'll remove this one and use the other.

**Comment by aftrosrs** [comment]
I guess ill make an issue post on that one then bc its still not working
